In [4]:
# dataframe management
import pandas as pd             

# numerical computation
import numpy as np

import re

# visualization library
import seaborn as sns
sns.set(style="white", color_codes=True)
sns.set_context(rc={"font.family":'sans',"font.size":24,"axes.titlesize":24,"axes.labelsize":24})   


# import matplotlib and allow it to plot inline
import matplotlib.pyplot as plt
%matplotlib inline

#for k-Means
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

from scipy.spatial.distance import cdist, pdist
# seaborn can generate several warnings, we ignore them
import warnings 
warnings.filterwarnings("ignore")

from bokeh.layouts import gridplot
from bokeh.plotting import figure

from bokeh.io import output_notebook, show
from bokeh.models import ColumnDataSource
output_notebook()

from datetime import datetime, timedelta, date
from scipy.stats import skew
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, ElasticNet, Lasso, LassoCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.datasets import load_boston

import statsmodels.api as sm


Loading BokehJS ...

In [5]:
import importlib #importlib.reload(WhatToReimport)
import data
import preprocessing
importlib.reload(data)
importlib.reload(preprocessing)

<module 'preprocessing' from 'C:\\Users\\andre\\Downloads\\cs412-hw\\hw5\\MachineLearningProject\\preprocessing.py'>

In [117]:
d=data.Dataset()

In [118]:
d.dataset.describe()

Music  Slow songs or fast songs        Dance         Folk  \
count  1007.000000               1008.000000  1006.000000  1005.000000   
mean      4.731877                  3.328373     3.113320     2.288557   
std       0.664049                  0.833931     1.170568     1.138916   
min       1.000000                  1.000000     1.000000     1.000000   
25%       5.000000                  3.000000     2.000000     1.000000   
50%       5.000000                  3.000000     3.000000     2.000000   
75%       5.000000                  4.000000     4.000000     3.000000   
max       5.000000                  5.000000     5.000000     5.000000   

           Country  Classical music      Musical          Pop         Rock  \
count  1005.000000      1003.000000  1008.000000  1007.000000  1004.000000   
mean      2.123383         2.956132     2.761905     3.471698     3.761952   
std       1.076136         1.252570     1.260845     1.161400     1.184861   
min       1.000000         1.000000     1.000000     1.000000     1.000000   
25%       1.000000         2.000000     2.000000     3.000000     3.000000   
50%       2.000000         3.000000     3.000000     4.000000     4.000000   
75%       3.000000         4.000000     4.000000     4.000000     5.000000   
max       5.000000         5.000000     5.000000     5.000000     5.000000   

       Metal or Hardrock         ...          Shopping centres  \
count        1007.000000         ...               1008.000000   
mean            2.361470         ...                  3.234127   
std             1.372995         ...                  1.323062   
min             1.000000         ...                  1.000000   
25%             1.000000         ...                  2.000000   
50%             2.000000         ...                  3.000000   
75%             3.000000         ...                  4.000000   
max             5.000000         ...                  5.000000   

       Branded clothing  Entertainment spending  Spending on looks  \
count       1008.000000             1007.000000        1007.000000   
mean           3.050595                3.201589           3.106256   
std            1.306321                1.188947           1.205368   
min            1.000000                1.000000           1.000000   
25%            2.000000                2.000000           2.000000   
50%            3.000000                3.000000           3.000000   
75%            4.000000                4.000000           4.000000   
max            5.000000                5.000000           5.000000   

       Spending on gadgets  Spending on healthy eating          Age  \
count          1010.000000                  1008.00000  1003.000000   
mean              2.870297                     3.55754    20.433699   
std               1.284970                     1.09375     2.828840   
min               1.000000                     1.00000    15.000000   
25%               2.000000                     3.00000    19.000000   
50%               3.000000                     4.00000    20.000000   
75%               4.000000                     4.00000    22.000000   
max               5.000000                     5.00000    30.000000   

           Height      Weight  Number of siblings  
count  990.000000  990.000000         1004.000000  
mean   173.514141   66.405051            1.297809  
std     10.024505   13.839561            1.013348  
min     62.000000   41.000000            0.000000  
25%    167.000000   55.000000            1.000000  
50%    173.000000   64.000000            1.000000  
75%    180.000000   75.000000            2.000000  
max    203.000000  165.000000           10.000000  

[8 rows x 139 columns]

In [119]:
d.dataset.shape

(1010, 150)

# Preprocessing

## Missing values

In [126]:
nulls = d.dataset.isnull().sum()
sorted([(x,y) for (x,y) in zip(nulls.index, nulls) if y>0], key=lambda x: x[1], reverse=True)

[]

In [121]:
#removing the rows in which the Empathy attrivute is null
#they are not necessary for train or testing
nullsEmpathy = d.dataset["Empathy"].isnull().sum()
print(nullsEmpathy)
d.dataset = d.dataset[d.dataset["Empathy"].notna()]

5


In [122]:
d.dataset["Empathy"].isnull().sum()

0

In [127]:
X = d.dataset.drop(columns=['Empathy'])
Y = d.dataset['Empathy']
Xt = X[900:]
X = X[:900]
Yt = Y[900:]
Y = Y[:900]

In [ ]:
#Split your data into 70% training data, 10% validation data and 20% test data.

In [ ]:
nullsEmpathy = d.dataset["Empathy"].isnull().sum()
print(nullsEmpathy)
d.dataset=preprocessing.removeNullTargetRows(d.dataset,"Empathy")

In [10]:
nullsEmpathy = d.dataset["Empathy"].isnull().sum()
print(nullsEmpathy)

0


In [123]:
categorical=d.dataset.select_dtypes(include="object", exclude="float")

In [124]:
d.dataset = d.dataset.select_dtypes(exclude="object")

#### Imputation of missing values

In [125]:
d.dataset=d.dataset.fillna(d.dataset.mean())

In [57]:
categorical.mode().loc[0]

Smoking                         tried smoking
Alcohol                        social drinker
Punctuality               i am always on time
Lying                               sometimes
Internet usage                few hours a day
Gender                                 female
Left - right handed              right handed
Education                    secondary school
Only child                                 no
Village - town                           city
House - block of flats         block of flats
Name: 0, dtype: object

In [59]:
categorical = categorical.fillna(categorical.mode().loc[0])

In [455]:
#categorical = categorical.fillna("null")

## One-hot encoding

In [60]:
categoricalDummied = pd.get_dummies(categorical)

In [61]:
categorical.shape

(1010, 11)

In [62]:
categoricalDummied.shape

(1010, 34)

In [63]:
d.dataset= pd.concat([d.dataset,categoricalDummied])

# Models

In [132]:
from sklearn.linear_model import LinearRegression
linReg = LinearRegression().fit(X, Y)

In [133]:
predict = linReg.predict(Xt)  

In [134]:
def getBinary(x):
    res=[]
    for i in range(len(x)):
        if(x[i]<=3):
            res.append(0)
        else:
            res.append(1)
    res = np.array(res)
    return res

In [135]:
check = Yt.values

In [136]:
predict = getBinary(predict)

In [137]:
check = getBinary(check)

In [138]:
np.mean(predict == check)

0.7142857142857143

In [139]:
y=getBinary(Yt.values)

In [151]:
y.shape

(105,)

In [154]:
Y.shape

(900,)

In [156]:
yl=getBinary(Y.values)

In [157]:
from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression()
logReg.fit(X, yl)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [158]:
predict2 = logReg.predict(Xt) 

In [159]:
#predict2 = getBinary(predict2)

In [160]:
predict2

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1])

In [161]:
np.mean(predict2 == check)

0.7428571428571429

In [214]:
y=getBinary(Y.values)

In [197]:
from sklearn.ensemble import RandomForestClassifier
model_simple = RandomForestClassifier()#20, "gini",10)
model_simple = model_simple.fit(Xpca, yl)

In [201]:
predict3 = model_simple.predict(Xtpca)

In [202]:
#predict3 = getBinary(predict3)

In [203]:
predict3

array([1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0])

In [199]:
from sklearn.decomposition import PCA
pca = PCA(n_components=50)
principalComponents = pca.fit_transform(d.dataset)
Xpca = pd.DataFrame(data = principalComponents)

In [200]:
from sklearn.decomposition import PCA
pca = PCA(n_components=50)
principalComponents = pca.fit_transform(Xt)
Xtpca = pd.DataFrame(data = principalComponents)

In [210]:
from sklearn.model_selection import cross_val_score
cross_val_score(model_simple, Xpca, yl, cv=20)

array([0.56521739, 0.62222222, 0.6       , 0.64444444, 0.55555556,
       0.64444444, 0.6       , 0.57777778, 0.53333333, 0.64444444,
       0.77777778, 0.57777778, 0.53333333, 0.62222222, 0.6       ,
       0.71111111, 0.64444444, 0.6       , 0.57777778, 0.68181818])

In [204]:
np.mean(predict3 == check)

0.6

In [ ]:
predict3.shape

In [ ]:
check.shape

In [158]:
from sklearn.linear_model import Lasso
model4 = Lasso()
model4 = model4.fit(X, Y)

In [159]:
predict4 = model4.predict(Xt)

In [160]:
predict4

array([3.98386772, 3.90664497, 4.01282624, 4.03213193, 3.7328938 ,
       3.95490919, 4.05143761, 3.84872792, 3.98386772, 4.01282624,
       3.96456203, 3.88733929, 3.98386772, 3.74254665, 4.01282624,
       4.03213193, 3.99352056, 3.8680336 , 3.94525634, 4.03213193,
       3.90664497, 3.83907507, 3.97421487, 4.09004899, 3.95490919,
       4.08039614, 3.74254665, 4.08039614, 4.03213193, 3.99352056,
       3.9356035 , 3.87768644, 3.91629782, 3.90664497, 4.06109046,
       3.94525634, 3.98386772, 3.82942223, 3.71358812, 4.06109046,
       3.83907507, 3.54948979, 3.98386772, 3.79081086, 3.97421487,
       3.69428243, 3.78115802, 3.9356035 , 3.96456203, 3.91629782,
       4.02247909, 3.71358812, 3.88733929, 3.94525634, 4.05143761,
       3.87368811, 3.79081086, 3.97421487, 3.62671253, 3.79081086,
       3.88733929, 3.98386772, 3.82942223, 3.79081086, 3.83907507,
       3.72324096, 3.9356035 , 3.6653239 , 3.35643293, 3.81011654,
       3.69428243, 3.91629782, 3.71358812, 3.9356035 , 3.64601

In [161]:
predict4=getBinary(predict4)

In [163]:
np.mean(predict4==check)

0.6285714285714286

In [ ]:
# It may be easier to have separate python files, but if you have a good way to make your code modular with one python file it is fine. What I mean is I should be able to run your testing code (e.g. loading your trained model -> get results on test data) only, instead of having to run the whole code for training -> testing.

In [211]:
import xgboost as xgb

In [462]:
from sklearn.model_selection import train_test_split
y=d.dataset['Empathy']
y=getBinary(y.values)
x=d.dataset.drop(columns=['Empathy'])
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.15, stratify=y)

In [422]:
#xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
            #    max_depth = 8, alpha = 10, n_estimators = 9000)
xg_reg = xgb.XGBClassifier(n_estimators = 9000)

In [423]:
xg_reg.fit(X_train,y_train)

preds = xg_reg.predict(X_test)

In [424]:
xg_reg.score(X_test,y_test)

0.7284768211920529

In [450]:
pca = PCA(n_components=110)
principalComponents = pca.fit_transform(d.dataset.drop(columns=['Empathy']))
Xpca = pd.DataFrame(data = principalComponents)

In [525]:
from sklearn.model_selection import train_test_split
y=d.dataset['Empathy']
y=getBinary(y.values)
x=d.dataset.drop(columns=['Empathy'])
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.1, random_state=123, stratify=y)

In [543]:
#xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
            #    max_depth = 8, alpha = 10, n_estimators = 9000)
xg_reg = xgb.XGBClassifier(objective = 'reg:logistic',max_depth = 5, n_estimators = 3000)

In [544]:
xg_reg.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=5, min_child_weight=1, missing=None, n_estimators=3000,
       n_jobs=1, nthread=None, objective='reg:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [545]:
preds = xg_reg.predict(X_test)

In [546]:
xg_reg.score(X_test,y_test)

0.7128712871287128

In [547]:
xg_reg.score(X_train,y_train)

1.0

In [537]:
d.dataset.drop(columns=['Empathy']).shape

(1005, 138)

In [551]:
data_dmatrix = xgb.DMatrix(data= d.dataset.drop(columns=['Empathy']), label=y)

In [552]:
params = {"objective":"reg:logistic",'colsample_bytree': 0.3,'learning_rate': 0.1,
                'max_depth': 5, 'alpha': 10}

cv_results = xgb.cv(dtrain=data_dmatrix, params=params, nfold=3,
                    num_boost_round=50,early_stopping_rounds=10,metrics="rmse", as_pandas=True, seed=123)

[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 10 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 16 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 10 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 18 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 8 extra nodes, 0 pruned nodes, max_depth=4
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 24 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning en

[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 24 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 24 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 18 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 18 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 18 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 24 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning e

In [553]:
cv_results.head()

train-rmse-mean  train-rmse-std  test-rmse-mean  test-rmse-std
0         0.493092        0.000684        0.495296       0.000355
1         0.486119        0.000487        0.490399       0.000142
2         0.478217        0.000326        0.485585       0.001383
3         0.472533        0.001454        0.481503       0.001941
4         0.467388        0.000494        0.478056       0.001342

In [405]:
np.mean(preds==y_test)

0.7284768211920529

In [392]:
preds

array([ 0.6403798 ,  0.39789385,  0.13559869,  0.44253185,  0.5363653 ,
        0.3591215 ,  0.7488286 ,  1.0237141 ,  0.4534249 ,  0.38871962,
        0.9981936 ,  0.9865401 ,  0.84068537,  0.7939675 ,  0.70866823,
        0.36939728,  0.78258705,  0.7433833 ,  0.16455597,  0.35075969,
        0.39985213,  1.0550575 ,  0.5330728 ,  0.8424365 ,  0.23221496,
        0.5966545 ,  0.85560167,  1.1549032 ,  0.91451657,  0.6247858 ,
        0.64675033,  0.8124499 ,  0.5803994 ,  0.82452273,  0.6431018 ,
        0.53773516,  0.48442534,  0.6484022 ,  0.556399  ,  0.62213856,
        0.8358965 ,  0.16133097, -0.11745381,  0.31892183,  0.51258826,
       -0.10482889,  1.0925102 ,  0.81104255,  0.9179917 ,  0.5875187 ,
        0.65203476,  0.6049895 ,  1.0467666 ,  0.63754255,  0.60420376,
        0.8833875 ,  0.4094634 ,  0.69907093,  0.75016105,  0.3766735 ,
        0.7548522 ,  0.97776973,  1.1691058 ,  0.6546159 ,  0.6100499 ,
        1.027824  ,  0.18218538,  0.60052484,  0.29500705,  0.47

In [300]:
xg_reg = xgb.XGBClassifier(n_estimators = 1000)

In [304]:
xg_reg.fit(X_train,y_train)

preds = xg_reg.predict(X_test)

In [305]:
np.mean(getBinary(preds)==getBinary(y_test.values))

0.7166666666666667

In [572]:
X_train.values

array([[  4.,   4.,   2., ..., 186.,  98.,   1.],
       [  5.,   3.,   5., ..., 180.,  80.,   1.],
       [  5.,   5.,   5., ..., 176.,  53.,   3.],
       ...,
       [  5.,   3.,   3., ..., 171.,  49.,   3.],
       [  5.,   4.,   5., ..., 176.,  55.,   1.],
       [  5.,   3.,   2., ..., 192.,  90.,   1.]])

In [592]:
import tensorflow as tf
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dense(512, activation=tf.nn.tanh),
  tf.keras.layers.Dense(256, activation=tf.nn.tanh),
  tf.keras.layers.Dropout(0.2), #it was 0.2
  tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train.values, y_train , epochs=200)
model.evaluate(X_test.values, y_test)

Epoch 1/200
904/904 [==============================] - 3s 3ms/step - loss: 0.8467 - acc: 0.5841
Epoch 2/200
904/904 [==============================] - 0s 525us/step - loss: 0.6852 - acc: 0.6051
Epoch 3/200
904/904 [==============================] - 0s 541us/step - loss: 0.7028 - acc: 0.6073
Epoch 4/200
904/904 [==============================] - 0s 530us/step - loss: 0.7011 - acc: 0.5918
Epoch 5/200
904/904 [==============================] - 1s 554us/step - loss: 0.6776 - acc: 0.6327
Epoch 6/200
904/904 [==============================] - 0s 544us/step - loss: 0.6833 - acc: 0.6294
Epoch 7/200
904/904 [==============================] - 0s 534us/step - loss: 0.6762 - acc: 0.6361
Epoch 8/200
904/904 [==============================] - 0s 533us/step - loss: 0.6849 - acc: 0.6195
Epoch 9/200
904/904 [==============================] - 0s 542us/step - loss: 0.6821 - acc: 0.6040
Epoch 10/200
904/904 [==============================] - 0s 534us/step - loss: 0.6829 - acc: 0.6162
Epoch 11/200
904/904 

KeyboardInterrupt: 

# prova SVM ! && cross validation per RandomForest