In [1]:
# dataframe management
import pandas as pd             

# numerical computation
import numpy as np

#import re

# visualization library
#import seaborn as sns
#sns.set(style="white", color_codes=True)
#sns.set_context(rc={"font.family":'sans',"font.size":24,"axes.titlesize":24,"axes.labelsize":24})   


# import matplotlib and allow it to plot inline
import matplotlib.pyplot as plt
#%matplotlib inline

#for k-Means
from sklearn.cluster import KMeans

from datetime import datetime, timedelta, date
#from scipy.stats import skew
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, ElasticNet, Lasso, LassoCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.datasets import load_boston

In [2]:
# for model persistence:
#https://scikit-learn.org/stable/modules/model_persistence.html
""">>> from sklearn import svm
>>> from sklearn import datasets
>>> clf = svm.SVC(gamma='scale')
>>> iris = datasets.load_iris()
>>> X, y = iris.data, iris.target
>>> clf.fit(X, y)  
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

>>> import pickle
>>> s = pickle.dumps(clf)
>>> clf2 = pickle.loads(s)
>>> clf2.predict(X[0:1])
array([0])
>>> y[0]
0"""
#---------------------

"""import pickle

a = {'hello': 'world'}

with open('filename.pickle', 'wb') as handle:
    pickle.dump(a, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('filename.pickle', 'rb') as handle:
    b = pickle.load(handle)

print a == b"""

"import pickle\n\na = {'hello': 'world'}\n\nwith open('filename.pickle', 'wb') as handle:\n    pickle.dump(a, handle, protocol=pickle.HIGHEST_PROTOCOL)\n\nwith open('filename.pickle', 'rb') as handle:\n    b = pickle.load(handle)\n\nprint a == b"

In [3]:
import importlib #importlib.reload(WhatToReimport)
import hw5
importlib.reload(hw5)
from sklearn.model_selection import train_test_split
import scipy

In [4]:
d=hw5.Dataset()

In [5]:
d.data.describe()

Music  Slow songs or fast songs        Dance         Folk  \
count  1007.000000               1008.000000  1006.000000  1005.000000   
mean      4.731877                  3.328373     3.113320     2.288557   
std       0.664049                  0.833931     1.170568     1.138916   
min       1.000000                  1.000000     1.000000     1.000000   
25%       5.000000                  3.000000     2.000000     1.000000   
50%       5.000000                  3.000000     3.000000     2.000000   
75%       5.000000                  4.000000     4.000000     3.000000   
max       5.000000                  5.000000     5.000000     5.000000   

           Country  Classical music      Musical          Pop         Rock  \
count  1005.000000      1003.000000  1008.000000  1007.000000  1004.000000   
mean      2.123383         2.956132     2.761905     3.471698     3.761952   
std       1.076136         1.252570     1.260845     1.161400     1.184861   
min       1.000000         1.000000     1.000000     1.000000     1.000000   
25%       1.000000         2.000000     2.000000     3.000000     3.000000   
50%       2.000000         3.000000     3.000000     4.000000     4.000000   
75%       3.000000         4.000000     4.000000     4.000000     5.000000   
max       5.000000         5.000000     5.000000     5.000000     5.000000   

       Metal or Hardrock         ...          Shopping centres  \
count        1007.000000         ...               1008.000000   
mean            2.361470         ...                  3.234127   
std             1.372995         ...                  1.323062   
min             1.000000         ...                  1.000000   
25%             1.000000         ...                  2.000000   
50%             2.000000         ...                  3.000000   
75%             3.000000         ...                  4.000000   
max             5.000000         ...                  5.000000   

       Branded clothing  Entertainment spending  Spending on looks  \
count       1008.000000             1007.000000        1007.000000   
mean           3.050595                3.201589           3.106256   
std            1.306321                1.188947           1.205368   
min            1.000000                1.000000           1.000000   
25%            2.000000                2.000000           2.000000   
50%            3.000000                3.000000           3.000000   
75%            4.000000                4.000000           4.000000   
max            5.000000                5.000000           5.000000   

       Spending on gadgets  Spending on healthy eating          Age  \
count          1010.000000                  1008.00000  1003.000000   
mean              2.870297                     3.55754    20.433699   
std               1.284970                     1.09375     2.828840   
min               1.000000                     1.00000    15.000000   
25%               2.000000                     3.00000    19.000000   
50%               3.000000                     4.00000    20.000000   
75%               4.000000                     4.00000    22.000000   
max               5.000000                     5.00000    30.000000   

           Height      Weight  Number of siblings  
count  990.000000  990.000000         1004.000000  
mean   173.514141   66.405051            1.297809  
std     10.024505   13.839561            1.013348  
min     62.000000   41.000000            0.000000  
25%    167.000000   55.000000            1.000000  
50%    173.000000   64.000000            1.000000  
75%    180.000000   75.000000            2.000000  
max    203.000000  165.000000           10.000000  

[8 rows x 139 columns]

In [6]:
d.data.shape

(1010, 150)

# Preprocessing

## Missing values of the target feature

In [7]:
nulls = d.data.isnull().sum()
sorted([(x,y) for (x,y) in zip(nulls.index, nulls) if y>0], key=lambda x: x[1], reverse=True)

[('Height', 20),
 ('Weight', 20),
 ('Passive sport', 15),
 ('Chemistry', 10),
 ('Geography', 9),
 ('Punk', 8),
 ('Latino', 8),
 ('Documentary', 8),
 ('Theatre', 8),
 ('Smoking', 8),
 ('Classical music', 7),
 ('Reggae, Ska', 7),
 ('Rock n roll', 7),
 ('Alternative', 7),
 ('Techno, Trance', 7),
 ('Countryside, outdoors', 7),
 ('Gardening', 7),
 ('Daily events', 7),
 ('Final judgement', 7),
 ('Criminal damage', 7),
 ('Compassion to animals', 7),
 ('Age', 7),
 ('Rock', 6),
 ('Swing, Jazz', 6),
 ('Movies', 6),
 ('PC', 6),
 ('Biology', 6),
 ('Reading', 6),
 ('Art exhibitions', 6),
 ('Writing', 6),
 ('Science and technology', 6),
 ('Friends versus money', 6),
 ('Giving', 6),
 ('Responding to a serious letter', 6),
 ('Number of siblings', 6),
 ('Gender', 6),
 ('Folk', 5),
 ('Country', 5),
 ('Psychology', 5),
 ('Economy Management', 5),
 ('Foreign languages', 5),
 ('Medicine', 5),
 ('Spiders', 5),
 ('Alcohol', 5),
 ('Prioritising workload', 5),
 ('Workaholism', 5),
 ('Self-criticism', 5),
 ('Em

We have to manage all these missing values. <br>
First of all I will remove all the rows that have the target feature "Empathy" to null because they have no use. 

In [8]:
#removing the rows in which the Empathy attrivute is null
#they are not necessary for train or testing
nullsEmpathy = d.data["Empathy"].isnull().sum()
#nullsEmpathy = 5
print("Number of rows with Empathy that is null: "+str(nullsEmpathy))
d.data = d.data[d.data["Empathy"].notna()]
print("Number of rows with Empathy that is null after: "+str(d.data["Empathy"].isnull().sum()))

Number of rows with Empathy that is null: 5
Number of rows with Empathy that is null after: 0


## Dealing with the categorical variables

Now I have to deal with the categorical variables. <br>
The first thing that I have to do is to impute the missing values of them. I will use the mode() (which is the most common value for each feature) to impute them.

In [9]:
#idea, provare a predirre i valori mancanti!

In [10]:
categorical=d.data.select_dtypes(include="object", exclude="float")

In [11]:
d.data = d.data.select_dtypes(exclude="object")

In [12]:
categorical.mode().loc[0]

Smoking                         tried smoking
Alcohol                        social drinker
Punctuality               i am always on time
Lying                               sometimes
Internet usage                few hours a day
Gender                                 female
Left - right handed              right handed
Education                    secondary school
Only child                                 no
Village - town                           city
House - block of flats         block of flats
Name: 0, dtype: object

In [13]:
print(categorical.isnull().sum())
categorical = categorical.fillna(categorical.mode().loc[0])
print(categorical.isnull().sum())

Smoking                   8
Alcohol                   5
Punctuality               2
Lying                     2
Internet usage            0
Gender                    6
Left - right handed       3
Education                 1
Only child                2
Village - town            4
House - block of flats    4
dtype: int64
Smoking                   0
Alcohol                   0
Punctuality               0
Lying                     0
Internet usage            0
Gender                    0
Left - right handed       0
Education                 0
Only child                0
Village - town            0
House - block of flats    0
dtype: int64


#### One-hot encoding of categorical variables

In [14]:
categoricalDummied = pd.get_dummies(categorical)

In [15]:
categorical.shape

(1005, 11)

In [16]:
categoricalDummied.shape

(1005, 34)

#### Imputation of missing values for the numerical features

I wil use the mean value of each attribute to impute the value of missing values for numerical features

In [17]:
d.data=d.data.fillna(d.data.mean())

In [18]:
d.data= pd.concat([d.data,categoricalDummied],axis=1)

In [19]:
nulls = d.data.isnull().sum()
sorted([(x,y) for (x,y) in zip(nulls.index, nulls) if y>0], key=lambda x: x[1], reverse=True)

[]

In [20]:
d.data.shape

(1005, 173)

# Training and Testing sets

In [21]:
#Split your data into 70% training data, 10% validation data and 20% test data. -> I will use cross validation

In [22]:
X = d.data.drop(columns=['Empathy'])
Y = d.data['Empathy']

I have now to trasform the target feature from a scale from 1 to 5 to a binary variable 0 (if the vale is 1,2 or 3) and 1 (4 ot 5).

In [23]:
def getBinary(x):
    res=[]
    for i in range(len(x)):
        if(x[i]<=3):
            res.append(0)
        else:
            res.append(1)
    res = np.array(res)
    return res

# Baseline

In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, stratify=Y, test_size=0.2, random_state=40)

In [25]:
X_train=np.array(X_train.values)
Y_train=np.array(Y_train.values)
X_test=np.array(X_test.values)
Y_test=np.array(Y_test.values)
Y=np.array(Y.values)

In [26]:
#use predict the most common or random

I will use as baseline a dump predictor that predict always the most frequent.

In [27]:
Y_train=getBinary(Y_train)
Y_test=getBinary(Y_test)
Y=getBinary(Y)

In [28]:
def trainBaseline(x):
    return scipy.stats.mode(x)[0][0]

In [29]:
mode=trainBaseline(Y_train)

In [30]:
def predictBaseline(test,mostfrequent):
    res=[]
    for i in range(len(test)):
        res.append(mostfrequent)
    return np.array(res)

In [31]:
predictions=predictBaseline(X_test,mode)

In [32]:
np.mean(predictions==Y_test)

0.6616915422885572

Usign the 20% of my dataset as testing set, this base predictor has an accuracy of 66%

# Model1

I start trying a Logistic Regression algoritm, I choose as solver the 'liblinear' one that should be one of the most suitable for binary classification in small databases. <br>
I'll use the L2 norm for the penalization and a value of C very small. C is the inverse of regularization strength, like in support vector machines, smaller values specify stronger regularization.

In [33]:
from sklearn.linear_model import LogisticRegression
logReg = LogisticRegression(solver='liblinear',random_state=123, C=0.1,penalty='l2', multi_class='ovr')
logReg.fit(X_train, Y_train)

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          n_jobs=None, penalty='l2', random_state=123, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [34]:
predict_train = logReg.predict(X_train) 

In [35]:
np.mean(predict_train == Y_train)

0.8208955223880597

In [36]:
predict_test = logReg.predict(X_test) 

In [37]:
np.mean(predict_test == Y_test)

0.7064676616915423

We have already achieved an accuracy of 82% on the training set and an accuracy of 70% on the testing one.

Now I will try to have a better idea of the real accuracy that that model can reach using a Stratified K-Fold cross validation.

In [48]:
X.shape

(1005, 172)

In [57]:
np.mean(cross_val_score(logReg, X, Y, cv=240))

0.7130555555555556

In [197]:
from sklearn.ensemble import RandomForestClassifier
model_simple = RandomForestClassifier()#20, "gini",10)
model_simple = model_simple.fit(Xpca, yl)

In [201]:
predict3 = model_simple.predict(Xtpca)

In [202]:
#predict3 = getBinary(predict3)

In [203]:
predict3

array([1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0])

In [199]:
from sklearn.decomposition import PCA
pca = PCA(n_components=50)
principalComponents = pca.fit_transform(d.data)
Xpca = pd.DataFrame(data = principalComponents)

In [200]:
from sklearn.decomposition import PCA
pca = PCA(n_components=50)
principalComponents = pca.fit_transform(Xt)
Xtpca = pd.DataFrame(data = principalComponents)

In [210]:
from sklearn.model_selection import cross_val_score
cross_val_score(model_simple, Xpca, yl, cv=20)

array([0.56521739, 0.62222222, 0.6       , 0.64444444, 0.55555556,
       0.64444444, 0.6       , 0.57777778, 0.53333333, 0.64444444,
       0.77777778, 0.57777778, 0.53333333, 0.62222222, 0.6       ,
       0.71111111, 0.64444444, 0.6       , 0.57777778, 0.68181818])

In [204]:
np.mean(predict3 == check)

0.6

In [ ]:
predict3.shape

In [ ]:
check.shape

In [158]:
from sklearn.linear_model import Lasso
model4 = Lasso()
model4 = model4.fit(X, Y)

In [159]:
predict4 = model4.predict(Xt)

In [160]:
predict4

array([3.98386772, 3.90664497, 4.01282624, 4.03213193, 3.7328938 ,
       3.95490919, 4.05143761, 3.84872792, 3.98386772, 4.01282624,
       3.96456203, 3.88733929, 3.98386772, 3.74254665, 4.01282624,
       4.03213193, 3.99352056, 3.8680336 , 3.94525634, 4.03213193,
       3.90664497, 3.83907507, 3.97421487, 4.09004899, 3.95490919,
       4.08039614, 3.74254665, 4.08039614, 4.03213193, 3.99352056,
       3.9356035 , 3.87768644, 3.91629782, 3.90664497, 4.06109046,
       3.94525634, 3.98386772, 3.82942223, 3.71358812, 4.06109046,
       3.83907507, 3.54948979, 3.98386772, 3.79081086, 3.97421487,
       3.69428243, 3.78115802, 3.9356035 , 3.96456203, 3.91629782,
       4.02247909, 3.71358812, 3.88733929, 3.94525634, 4.05143761,
       3.87368811, 3.79081086, 3.97421487, 3.62671253, 3.79081086,
       3.88733929, 3.98386772, 3.82942223, 3.79081086, 3.83907507,
       3.72324096, 3.9356035 , 3.6653239 , 3.35643293, 3.81011654,
       3.69428243, 3.91629782, 3.71358812, 3.9356035 , 3.64601

In [161]:
predict4=getBinary(predict4)

In [163]:
np.mean(predict4==check)

0.6285714285714286

In [ ]:
# It may be easier to have separate python files, but if you have a good way to make your code modular with one python file it is fine. What I mean is I should be able to run your testing code (e.g. loading your trained model -> get results on test data) only, instead of having to run the whole code for training -> testing.

In [211]:
import xgboost as xgb

In [462]:
from sklearn.model_selection import train_test_split
y=d.data['Empathy']
y=getBinary(y.values)
x=d.data.drop(columns=['Empathy'])
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.15, stratify=y)

In [422]:
#xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
            #    max_depth = 8, alpha = 10, n_estimators = 9000)
xg_reg = xgb.XGBClassifier(n_estimators = 9000)

In [423]:
xg_reg.fit(X_train,y_train)

preds = xg_reg.predict(X_test)

In [424]:
xg_reg.score(X_test,y_test)

0.7284768211920529

In [450]:
pca = PCA(n_components=110)
principalComponents = pca.fit_transform(d.data.drop(columns=['Empathy']))
Xpca = pd.DataFrame(data = principalComponents)

In [525]:
from sklearn.model_selection import train_test_split
y=d.data['Empathy']
y=getBinary(y.values)
x=d.data.drop(columns=['Empathy'])
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.1, random_state=123, stratify=y)

In [543]:
#xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
            #    max_depth = 8, alpha = 10, n_estimators = 9000)
xg_reg = xgb.XGBClassifier(objective = 'reg:logistic',max_depth = 5, n_estimators = 3000)

In [544]:
xg_reg.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=5, min_child_weight=1, missing=None, n_estimators=3000,
       n_jobs=1, nthread=None, objective='reg:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [545]:
preds = xg_reg.predict(X_test)

In [546]:
xg_reg.score(X_test,y_test)

0.7128712871287128

In [547]:
xg_reg.score(X_train,y_train)

1.0

In [537]:
d.data.drop(columns=['Empathy']).shape

(1005, 138)

In [551]:
data_dmatrix = xgb.DMatrix(data= d.data.drop(columns=['Empathy']), label=y)

In [552]:
params = {"objective":"reg:logistic",'colsample_bytree': 0.3,'learning_rate': 0.1,
                'max_depth': 5, 'alpha': 10}

cv_results = xgb.cv(dtrain=data_dmatrix, params=params, nfold=3,
                    num_boost_round=50,early_stopping_rounds=10,metrics="rmse", as_pandas=True, seed=123)

[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 10 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 16 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 10 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 18 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 8 extra nodes, 0 pruned nodes, max_depth=4
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 24 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning en

[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 24 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 24 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 18 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 18 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 18 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning end, 1 roots, 24 extra nodes, 0 pruned nodes, max_depth=5
[19:10:39] C:\Users\Administrator\Desktop\xgboost\src\tree\updater_prune.cc:74: tree pruning e

In [553]:
cv_results.head()

train-rmse-mean  train-rmse-std  test-rmse-mean  test-rmse-std
0         0.493092        0.000684        0.495296       0.000355
1         0.486119        0.000487        0.490399       0.000142
2         0.478217        0.000326        0.485585       0.001383
3         0.472533        0.001454        0.481503       0.001941
4         0.467388        0.000494        0.478056       0.001342

In [405]:
np.mean(preds==y_test)

0.7284768211920529

In [392]:
preds

array([ 0.6403798 ,  0.39789385,  0.13559869,  0.44253185,  0.5363653 ,
        0.3591215 ,  0.7488286 ,  1.0237141 ,  0.4534249 ,  0.38871962,
        0.9981936 ,  0.9865401 ,  0.84068537,  0.7939675 ,  0.70866823,
        0.36939728,  0.78258705,  0.7433833 ,  0.16455597,  0.35075969,
        0.39985213,  1.0550575 ,  0.5330728 ,  0.8424365 ,  0.23221496,
        0.5966545 ,  0.85560167,  1.1549032 ,  0.91451657,  0.6247858 ,
        0.64675033,  0.8124499 ,  0.5803994 ,  0.82452273,  0.6431018 ,
        0.53773516,  0.48442534,  0.6484022 ,  0.556399  ,  0.62213856,
        0.8358965 ,  0.16133097, -0.11745381,  0.31892183,  0.51258826,
       -0.10482889,  1.0925102 ,  0.81104255,  0.9179917 ,  0.5875187 ,
        0.65203476,  0.6049895 ,  1.0467666 ,  0.63754255,  0.60420376,
        0.8833875 ,  0.4094634 ,  0.69907093,  0.75016105,  0.3766735 ,
        0.7548522 ,  0.97776973,  1.1691058 ,  0.6546159 ,  0.6100499 ,
        1.027824  ,  0.18218538,  0.60052484,  0.29500705,  0.47

In [300]:
xg_reg = xgb.XGBClassifier(n_estimators = 1000)

In [304]:
xg_reg.fit(X_train,y_train)

preds = xg_reg.predict(X_test)

In [305]:
np.mean(getBinary(preds)==getBinary(y_test.values))

0.7166666666666667

In [572]:
X_train.values

array([[  4.,   4.,   2., ..., 186.,  98.,   1.],
       [  5.,   3.,   5., ..., 180.,  80.,   1.],
       [  5.,   5.,   5., ..., 176.,  53.,   3.],
       ...,
       [  5.,   3.,   3., ..., 171.,  49.,   3.],
       [  5.,   4.,   5., ..., 176.,  55.,   1.],
       [  5.,   3.,   2., ..., 192.,  90.,   1.]])

In [592]:
import tensorflow as tf
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dense(512, activation=tf.nn.tanh),
  tf.keras.layers.Dense(256, activation=tf.nn.tanh),
  tf.keras.layers.Dropout(0.2), #it was 0.2
  tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train.values, y_train , epochs=200)
model.evaluate(X_test.values, y_test)

Epoch 1/200
904/904 [==============================] - 3s 3ms/step - loss: 0.8467 - acc: 0.5841
Epoch 2/200
904/904 [==============================] - 0s 525us/step - loss: 0.6852 - acc: 0.6051
Epoch 3/200
904/904 [==============================] - 0s 541us/step - loss: 0.7028 - acc: 0.6073
Epoch 4/200
904/904 [==============================] - 0s 530us/step - loss: 0.7011 - acc: 0.5918
Epoch 5/200
904/904 [==============================] - 1s 554us/step - loss: 0.6776 - acc: 0.6327
Epoch 6/200
904/904 [==============================] - 0s 544us/step - loss: 0.6833 - acc: 0.6294
Epoch 7/200
904/904 [==============================] - 0s 534us/step - loss: 0.6762 - acc: 0.6361
Epoch 8/200
904/904 [==============================] - 0s 533us/step - loss: 0.6849 - acc: 0.6195
Epoch 9/200
904/904 [==============================] - 0s 542us/step - loss: 0.6821 - acc: 0.6040
Epoch 10/200
904/904 [==============================] - 0s 534us/step - loss: 0.6829 - acc: 0.6162
Epoch 11/200
904/904 

KeyboardInterrupt: 

# prova SVM ! && cross validation per RandomForest